language: clojure
script:
  - lein expectations
  - lein with-profile -dev,+uberjar cljsbuild once
  - lein cljfmt check | ":"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b1bef7f8990cf47b0417
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
